### ISSUE TITLE
react-docgen no longer has react-docgen/dist/babylon

### ISSUE THREAD

**Issue by reintroducing** [siddharthkp/react-docgen-external-proptypes-handler#5]
This is causing an error in version 8.0.5+ of react-styleguidist now when using this plugin.
```
Cannot find module 'react-docgen/dist/babylon'
npx styleguidist server --open exited with code 1
```

**Comment by siddharthkp** [comment]
Great catch! Do you know the replacement for it?

**Comment by danez** [comment]
The replacement is: `react-docgen/dist/babelParser`.

I guess doing this should make it possible for old and new versions to work:

```js
let babylon
try {
    babylon = require(`react-docgen/dist/babelParser`).default
} catch (e) {
   babylon = require(`react-docgen/dist/babylon`).default
}
```

**Comment by reintroducing** [comment]
Thanks @danez for following up on this. @siddharthkp any chance we can get an updated version with the changes so we can upgrade react-styleguidist without issue?

**Comment by Slowl** [comment]
Thanks @danez ! It fixed my issue but now, docgen return an empty object for every components that require an external variable to define some proptypes 
Any idea on how to fix that ?

**Comment by siddharthkp** [comment]
Added @danez as a collaborator to both this repo and package on npm to take this forward

@danez You cool with that?

**Comment by Slowl** [comment]
@reintroducing I personally downgraded react-docgen to a stable version until a fix is found for react-docgen >v3

**Comment by danez** [comment]
> @danez You cool with that?

Okay, thanks.

**Comment by danez** [comment]
Okay fixed in 1.0.1.

**Comment by reintroducing** [comment]
Hmm, I just updated and while it does compile, there are now errors for the components that had the setup like I mentioned here: https://github.com/siddharthkp/react-docgen-external-proptypes-handler/issues/1
`Warning: Cannot parse src/TextInput/TextInput.jsx: TypeError: options.parser.parse is not a function`

I can actually fix the errors by destructuring the propTypes like so:
```static propTypes = {
    ...TextInputPropTypes,
};```

However that doesn't actually fix the propTypes listed in the style guide.

Prior to update: https://www.dropbox.com/s/yhh131i6fvxeqj8/Screenshot%202018-12-13%2007.59.33.png?dl=0

After update: https://www.dropbox.com/s/yhh131i6fvxeqj8/Screenshot%202018-12-13%2007.59.33.png?dl=0

Post update, only the defaultProps show. Any idea whats going on?

**Comment by danez** [comment]
Can you try again with 1.0.2? It should work now. Sorry for the mistake.

**Comment by reintroducing** [comment]
@danez Please don't be sorry, you're helping out on an OSS project, I really appreciate you even taking time to do this.

As for the update, it fixed most of the components that were erroring last time except one. The new error I now see in that component is `Warning: Cannot parse src/TextInput/TextInput.jsx: TypeError: Cannot read property 'loc' of null`.

That component's propTypes are simply `static propTypes = TextInputPropTypes;` and it does work with v1.0.0 and react-styleguidist v8.0.4. Upgrading both to v1.0.2 and v8.0.5+ breaks it with the above error.

**Comment by reintroducing** [comment]
@coreybruyere unfortunately no, and i've just stayed on v8.0.4 of react-styleguidist as a result to make sure i'm not getting the errors.
